# Generated by Django 6.0.7 on 2026-08-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='surface',
            field=models.CharField(blank=True, choices=[('hard', 'Hard'), ('clay', 'Clay'), ('grass', 'Grass')], default='', max_length=20),
        ),
    ]
