# Generated by Django 6.0.7 on 2026-07-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('admin', 'Admin')], default='player', max_length=20),
        ),
    ]
