# Generated by Django 6.0.7 on 2026-07-20 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lesson_type', models.CharField(choices=[('private', 'Private Lesson'), ('semi_private', 'Semi-Private Lesson'), ('group', 'Group Lesson'), ('fitness', 'Fitness Session'), ('padel', 'Padel Lesson')], max_length=30)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('maximum_players', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('court_type', models.CharField(choices=[('tennis', 'Tennis'), ('padel', 'Padel')], default='tennis', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='coach_pictures/default.png', upload_to='coach_pictures/')),
                ('title', models.CharField(default='Academy Coach', max_length=100)),
                ('specialty', models.CharField(choices=[('development', 'Player Development'), ('high_performance', 'High Performance'), ('junior', 'Junior Tennis'), ('doubles', 'Doubles'), ('fitness', 'Fitness and Conditioning'), ('padel', 'Padel')], max_length=30)),
                ('biography', models.TextField()),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('certifications', models.CharField(blank=True, max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('preferred_location', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=20)),
                ('preferred_surface', models.CharField(choices=[('hard', 'Hard'), ('clay', 'Clay'), ('grass', 'Grass')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bookings', to='coaches.coach')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bookings', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_booking', to='reservations.reservation')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='coaches.lessonprogram')),
            ],
        ),
    ]
