# Generated by Django 6.0.7 on 2026-07-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogram',
            name='price',
        ),
        migrations.AddField(
            model_name='coach',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=75, max_digits=7),
        ),
    ]
