# Generated by Django 6.0.7 on 2026-07-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_remove_lessonprogram_price_coach_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coach',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='coaches.lessonprogram'),
        ),
        migrations.AddField(
            model_name='coach',
            name='utr_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
