# Generated by Django 6.0.7 on 2026-07-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_coach_nationality_coach_programs_coach_utr_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
