# Generated by Django 6.0.7 on 2026-07-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_alter_coach_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
    ]
